### ISSUE TITLE
yarn  怎么一直报错，解决不了

### ISSUE THREAD

**Issue by 1029173607** [JellyBool/zhihu-app#2]
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.0.15: The platform "win32" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "laravel-elixir-vue-2 > sass-loader@4.0.2" has unmet peer dependency "node-sass@^3.4.2".
warning "laravel-elixir-vue-2 > sass-loader@4.0.2" has unmet peer dependency "webpack@^1.12.6 || ^2.1.0-beta".
[4/4] Building fresh packages...
error D:\phpStudy\WWW\zhihu\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: D:\phpStudy\WWW\zhihu\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe D:\phpStudy\WWW\zhihu\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\phpStudy\\WWW\\zhihu\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.6.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\phpStudy\WWW\zhihu\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\phpStudy\WWW\zhihu\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\phpStudy\WWW\zhihu\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\phpStudy\WWW\zhihu\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\phpStudy\WWW\zhihu\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at D:\phpStudy\WWW\zhihu\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\phpStudy\WWW\zhihu\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\phpStudy\WWW\zhihu\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\phpStudy\WWW\zhihu\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\phpStudy\WWW\zhihu\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\phpStudy\WWW\zhihu\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at D:\phpStudy\WWW\zhihu\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\phpStudy\WWW\zhihu\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\phpStudy\WWW\zhihu\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\phpStudy\WWW\zhihu\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\phpStudy\WWW\zhihu\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\phpStudy\WWW\zhihu\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at D:\phpStudy\WWW\zhihu\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\phpStudy\WWW\zhihu\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\phpStudy\WWW\zhihu\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\phpStudy\WWW\zhihu\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\phpStudy\WWW\zhihu\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\phpStudy\WWW\zhihu\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at D:\phpStudy\WWW\zhihu\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (D:\phpStudy\WWW\zhihu\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at D:\phpStudy\WWW\zhihu\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at D:\phpStudy\WWW\zhihu\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\phpStudy\\WWW\\zhihu\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\phpStudy\WWW\zhihu\node_modules\node-sass
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by JellyBool** [comment]
> The platform "win32" is incompatible with this module.

32位 windows 原因？
